### ISSUE TITLE
Error by Import database view

### ISSUE THREAD

**Issue by andelwol26** [zhmu/romdb#1]
Hello,

when i follow your instruction i got the following error. 
do you have any idea what could be my problem?

![grafik](https://user-images.githubusercontent.com/39248391/62535830-ad896a00-b84c-11e9-96d2-468b76710ec8.png)

**Comment by zhmu** [comment]
It seems the instructions are not quite correct: the views.sql file only creates the 'all_imageid' view which is only used by the PHP website, not by the import process.

Can you first try importing all the data (as outlined in the instructions) and once that is done, execute the " \i views.sql" ?

**Comment by andelwol26** [comment]
works perfekt
